#define ENCODER_A_PINS { GP0, GP6 }
#define ENCODER_B_PINS { GP1, GP7 }

#define DIP_SWITCH_PINS { GP5, GP2 }

#define HAL_USE_I2C TRUE
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP16
#define I2C1_SCL_PIN GP17
#define OLED_DISPLAY_128X64
#define OLED_DISPLAY_WIDTH 128
#define OLED_DISPLAY_HEIGHT 64